description: single-operation-experiment
params: ["--Seed=1"]
args:
  func: OBF_FUNC
variants:
  - name: flatten
    procedure:
      - ["--Transform=Flatten", "--FlattenSplitBasicBlocks=true", "--Functions={func}",
          "--Transform=CleanUp", "--CleanUpKinds=annotations,removeUnusedFunctions"]
    format: true

  - name: dead-code-insertion
    procedure:
      - ["--Transform=InitEntropy", "--Functions={func}", "--InitEntropyKinds=vars",
          "--Transform=InitOpaque", "--Functions={func}", "--InitOpaqueCount=1", "--InitOpaqueStructs={opaque_structs}",
          "--Transform=AddOpaque", "--Functions={func}", "--AddOpaqueKinds=*", "--AddOpaqueCount={num_opaque_per_function}", "--AddOpaqueStructs={opaque_structs}",
          "--Transform=CleanUp", "--CleanUpKinds=annotations,removeUnusedFunctions"]
    args:
      num_opaque_per_function: 2
      opaque_structs: env,list # list, array, input, env, *
  
  - name: block-fission
    procedure:
      - ["--Transform=Flatten", "--FlattenSplitBasicBlocks=true", "--Functions={func}"]
      - ["--Transform=InitEntropy", "--Functions={func}", "--InitEntropyKinds=vars",
          "--Transform=InitOpaque", "--Functions={func}", "--InitOpaqueCount=1", "--InitOpaqueStructs={opaque_structs}",
          "--Transform=AddOpaque", "--Functions={func}", "--AddOpaqueKinds=*", "--AddOpaqueCount={num_opaque_per_function}", "--AddOpaqueStructs={opaque_structs}",
          "--Transform=CleanUp", "--CleanUpKinds=annotations,removeUnusedFunctions"]
    format: true
    args:
      num_opaque_per_function: 2
      opaque_structs: env

  - name: loop-unrolling
    # not supported
  - name: irrelevant-code-insertion
    # not supported
  - name: loop-fission
    # not supported
