description: single-operation-experiment
params: ["--Seed=1"]
args:
  # single or multiple (separated by colon) function to obfuscate
  func: OBF_FUNC

  # options to postprocess obfuscated code
  cleanup_kinds: removeUnusedFunctions

  # number of opaque data stuructures per program
  num_opaques: 2

variants:
  # removes structured control flow
  - name: flatten
    procedure:
      - ["--Transform=Flatten", "--FlattenSplitBasicBlocks=true", "--Functions={func}",
          "--Transform=CleanUp", "--CleanUpKinds={cleanup_kinds}"]
    format: true

  # insert code that we never execute. this is done by introducing if-statements
  # with condition on boolean and integer expressions that have a known value
  - name: dead-code-insertion
    procedure:
      - ["--Transform=InitEntropy", "--Functions={func}", "--InitEntropyKinds=vars",
          "--Transform=InitOpaque", "--Functions={func}", "--InitOpaqueCount={num_opaques}", "--InitOpaqueStructs={opaque_structs}",
          # "--Transform=UpdateOpaque", "--Functions={func}",
          "--Transform=AddOpaque", "--Functions={func}", "--AddOpaqueKinds={opaque_kinds}", "--AddOpaqueCount={num_opaque_per_function}", "--AddOpaqueStructs={opaque_structs}",
          "--Transform=CleanUp", "--CleanUpKinds={cleanup_kinds}"]
    args:
      num_opaque_per_function: 2
      opaque_structs: env,list # list, array, input, env, *
      opaque_kinds: call,bug,true,junk,question # call, bug, true, junk, fake, question, *
  
  # split up basic blocks and rearrange into multiple basic blocks with
  # opaque predicates and gotos connecting them.
  # the implementation here is flattening + deadcode insertion
  - name: block-fission
    procedure:
      - ["--Transform=Flatten", "--FlattenSplitBasicBlocks=true", "--Functions={func}"]
      - ["--Transform=InitEntropy", "--Functions={func}", "--InitEntropyKinds=vars",
          "--Transform=InitOpaque", "--Functions={func}", "--InitOpaqueCount={num_opaques}", "--InitOpaqueStructs={opaque_structs}",
          "--Transform=AddOpaque", "--Functions={func}", "--AddOpaqueKinds={opaque_kinds}", "--AddOpaqueCount={num_opaque_per_function}", "--AddOpaqueStructs={opaque_structs}",
          "--Transform=CleanUp", "--CleanUpKinds={cleanup_kinds}"]
    format: true
    args:
      num_opaque_per_function: 2
      opaque_structs: env,list
      opaque_kinds: call,bug,true,junk,question # call, bug, true, junk, fake, question, *

  - name: loop-unrolling
    # not supported
  - name: irrelevant-code-insertion
    # not supported
  - name: loop-fission
    # not supported
