description: block-fission
params: ["--Seed=1"]
variants:
  - name: basic
    procedure:
      # - ["--Transform=Flatten", "--FlattenSplitBasicBlocks=true", "--Functions={func}"]
      - ["--Transform=InitEntropy", "--Functions={func}", "--InitEntropyKinds=vars",
          "--Transform=InitOpaque", "--Functions={func}", "--InitOpaqueCount=1", "--InitOpaqueStructs=env",
          "--Transform=AddOpaque", "--Functions={func}",
          "--Transform=CleanUp", "--CleanUpKinds=annotations,compress,removeUnusedFunctions"]
    format: true
    args:
      func: OBF_FUNC